var express = require("express");
var router = express.Router();

router.post("/nodes", function (req, res) {
    const nodes = {
    "data":{
       "id":5,
       "type":"folder",
       "title":"root",
       "ord":110
    },
    "childs":[
       {
          "data":{
             "id":74,
             "type":"file",
             "title":"file1.jpg",
             "mime":"image/jpeg",
             "ord":110
          },
          "childs":null
       },
       {
          "data":{
             "id":75,
             "type":"file",
             "title":"file2.png",
             "mime":"image/png",
             "ord":110
          },
          "childs":null
       },
       {
          "data":{
             "id":76,
             "type":"file",
             "title":"file3.jpg",
             "mime":"image/jpeg",
             "ord":110
          },
          "childs":null
       },
       {
          "data":{
             "id":89,
             "type":"file",
             "title":"file4.gif",
             "mime":"image/gif",
             "ord":110
          },
          "childs":null
       },
       {
          "data":{
             "id":90,
             "type":"file",
             "title":"file5.JPG",
             "mime":"image/jpeg",
             "ord":110
          },
          "childs":null
       },
       {
          "data":{
             "id":187,
             "type":"file",
             "title":"file6.jpg",
             "mime":"image/jpeg",
             "ord":110
          },
          "childs":null
       },
       {
          "data":{
             "id":6,
             "type":"folder",
             "title":"foldername",
             "ord":110
          },
          "childs":[
             {
                "data":{
                   "id":20,
                   "type":"file",
                   "title":"file7.jpg",
                   "mime":"image/jpeg",
                   "ord":110
                },
                "childs":null
             },
             {
                "data":{
                   "id":21,
                   "type":"file",
                   "title":"file8.jpg",
                   "mime":"image/jpeg",
                   "ord":110
                },
                "childs":null
             },
             {
                "data":{
                   "id":22,
                   "type":"file",
                   "title":"file9.jpg",
                   "mime":"image/jpeg",
                   "ord":110
                },
                "childs":null
             },
             {
                "data":{
                   "id":23,
                   "type":"file",
                   "title":"file10.jpg",
                   "mime":"image/jpeg",
                   "ord":110
                },
                "childs":null
             },
             {
                "data":{
                   "id":24,
                   "type":"file",
                   "title":"file11.jpg",
                   "mime":"image/jpeg",
                   "ord":110
                },
                "childs":null
             }
          ]
       }
    ]
 }
 res.json(nodes);
});

 module.exports = router;
